### ISSUE TITLE
主机域名解析参数

### ISSUE THREAD

**Issue by tlj1339** [DarthPestilane/aliddns#1]
DOMAIN=你需要在阿里云添加的主机域名解析，如home.test.com
没有把这一项放到环境变量中么，直接在环境变量中设置，而不是执行命令

**Comment by DarthPestilane** [comment]
如果把domain设置在环境变量里，我们想要修改解析的域名就需要做:

1. 修改 .env
2. 重启服务

有些麻烦，不如直接修改请求参数来的简单。
再一点是这样一来(domain配置在env里)，就把域名和整个服务耦合在一起了。
